services:
    mongo:
        image: mongo:latest
        container_name: mongo
        command: [ "--replSet", "rs0", "--bind_ip_all" ]
        ports:
            - "27017:27017"
        healthcheck:
            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
            interval: 5s
            timeout: 3s
            retries: 30
        volumes:
            - mongo_data:/data/db

    mongo-init-replica:
        image: mongo:latest
        container_name: mongo-init-replica
        depends_on:
            - mongo
        entrypoint: >
            bash -lc " sleep 3 && mongosh --host mongo:27017 --eval \"
              rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27017'}]});
              rs.status();
            \" "

    elasticsearch:
        image: elasticsearch:7.8.1
        container_name: elastic
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 30
        volumes:
            - es_data:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.8.1
        container_name: kibana
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - XPACK_SECURITY_ENABLED=false
        ports:
            - "5601:5601"

    monstache:
        image: rwynn/monstache:latest
        container_name: monstache
        depends_on:
            - mongo
            - elasticsearch
        command: [ "-f", "./monstache.toml" ]
        volumes:
            - ./monstache.config.toml:/config/monstache.config.toml:ro

volumes:
    mongo_data:
    es_data:
